---
title: 'RNI1006 Regression and Nonparametric Inference'
author: 'Computer Lab 1 (Week 1)'
output:
  word_document: default
  html_notebook:
    theme: flatly
  pdf_document: default
  html_document:
    highlight: haddock
    theme: flatly
---

## Learning Check

When you complete this session, you will be able to:

1. revise *one sample t-test*;
2. find the *rank transformation* for a set of data;
3. state *the null and alternative hypotheses* that are used for the analysis of
data using *the Wilcoxon signed rank test for one sample*;
4. find *the mean and the standard deviation* of the sampling distribution of the Wilcoxon signed rank test statistic $W$ under the
null hypothesis;
5. find *the P-value* for the Wilcoxon signed rank test using the Normal
approximation with the continuity correction;
6. use computer output to determine the results of *the Wilcoxon signed rank test for one sample*, for both the exact and approximate methods.

In this unit we will be  using _R_ to carry out statistical analyses via the interface _RStudio_. As you work through the unit you should be building on the familiarity with basic _R_ syntax and data manipulation that you gained in the prerequisite course STAT1005. 

While you may be used to typing commands directly into the interactive _R_ console, at the ">" prompt, here you will be introduced to _R_ script (.R) and _R_ Markdown (.Rmd) files, where series of commands are kept together for computations and analyses to be carried out in the current session or saved for later use. Code saved in these files can be run from within _RStudio_ using short cut keys. 

## OVERVIEW

In Lecture Week 1, we have covered the single-sample t-test (revision) and the Wilcoxon signed rank test for one sample. You are expected to be familiar with implementation and interpretation of these tests using both explicit computation of the test statistics, as well as application of appropriate inbuilt _R_ test functions.   

1.  You should be thoroughly familiar with input and ouput of the test functions `t.test`

2.  You should become conversant with use of basic summary, computational and plotting commands. Applicable ones for this workshop include `boxplot`,  `plot`,  `summary`, `sort`, `sum`,  `sign` (applicable for numeric vectors), and `table` (which counts unique values of a vector). 

3. You will be introduced with the function `wilcox.test`

Don't forget to check the `help` for any function that you are not familiar with by typing either '?function_name' or 'help(function_name)'. For the test procedures especially, it is important to understand the arguments of the function. 

Relevant practice exercises for this topic are found in Blackboard under Practice Test 1. It would be helpful to have attempted these exercises before coming to the lab.

### Recap of Wilcoxon Signed-rank Test: One sample  

1. Draw an simple random sample (SRS) of size $n$ from a population, say $X_1, X_2, ..., X_n.$ 
2. Suppose we test  $H_0: θ=θ_0.$
3. Calculate $X_i’ = X_i - θ_0, i=1,2,..., n.$
4. *Remove the zero differences*, if any.
5. Rank the absolute values of these differences $|X_i’|$ in step 4.
6. The sum $W^+$ of the ranks for the positive differences is the Wilcoxon signed rank statistic. 
7. _Approximate method._ When there are ties, calculate the P-value for the Wilcoxon signed rank statistic using the Normal approximation with the continuity correction or `wilcox.test` using the argument `Exact=False`. If the distribution of the responses is not affected by the different treatments within pairs, then $W^+$ has mean:
$$\mu_{W^+} =\frac{n(n+1)}{4}$$ 
and standard deviation:
$$ \sigma_{W^+} = \sqrt{\frac{n(n+1)(2n+1)}{24}}.$$

8. _Exact method._ When there are no zero differences and no ties, R provides the exact calculation of the p-value using either _psignrank_ or _wilcox.test_ using the argument `Exact=True`
9. The Wilcoxon signed rank test rejects the hypothesis that there are no systematic differences between $X_i’$ under $H_0$ when the rank sum W+ is far from its mean.

The function `wilcox.test` calculates an exact p-value *if the samples contain less than 50 finite values and there are no ties* using the argument `Exact=True.` Otherwise (`Exact=False.`), a normal approximation is used.

### Using the Normal approximation with the continuity correction 

The distribution of the signed rank statistic $W^+$ when the null hypothesis of no difference is true becomes approximately Normal as the sample size becomes large.  

We can then use Normal probability calculations (with the continuity correction) to obtain approximate P-values for $W^+$ by calculating and its probabilities

$$ z=\frac{(W^+ - \mu_{W^+})}{\sigma_{W^+}}.$$


**Question 1: Adapted from Walpole 16.1**    

The following data represent the time, in minutes, that a patient has to wait during 12 visits to a doctor's office before being seen by the doctor:

17, 15, 20, 20, 32, 28, 12, 26, 25, 25, 35, 24

a.  You are to use a t-test to evaluate whether or not it would be reasonable for the doctor to claim that patients do not, on average, have to wait more than 20 minutes before being admitted to the examination room.     

    +  Examine a boxplot of these data and comment on the suitability of a t-test for assessing this claim.    
    +  Use the _R_ function 't.test', with appropriate input arguments, to implement the test. 
    +  Conduct the 6 steps hypothesis testing as explained in the lecture based on the R output.  


b.  Perform a Wilcoxon Signed-Rank test manually to assess the doctor's claim.

    + State the formal null and alternative hypotheses appropriate for this test. How does this compare with that appropriate for the t-test above?  
    + Calculate $X_i’ = X_i - 20, i=1,2,..., n.$
    + Rank the absolute values of these differences $|x_i’|$ excluding the ties, if any.
    + Calculate $W^+$ 
    + Find the P-value for the Wilcoxon signed rank statistic using the Normal approximation with the continuity correction.
    
c. Use a Wilcoxon Signed-Rank test in R to assess the doctor's claim. Summarise the results using the 6 steps hypothesis testing as explained in the lecture based on the R output.

**Question 2: Adapted from Moore et al (2017) Ex 15.35. Radon detectors** 

How accurate are radon detectors of a type sold to homeowners? To answer this question, university researchers placed 12 detectors in a chamber that exposed them to 105 picocuries per liter (pCi/l) of
radon. The detector readings are as follows

91.9  97.8 111.4  122.3  105.4  95.0  103.8  99.6  96.6  119.3  104.8  101.7

We wonder if the median reading differs significantly from the true value 105.

a. Use a t-test to evaluate whether the mean reading differs significantly
from the true value 105.

b. Graph the data, and comment on skewness and
outliers. Comment whether a nonparametric test is appropriate.

c. We would like to test hypotheses about the median $\eta$
reading from home radon detectors:

$H_0 : \eta=105$    $H_1 : \eta \not= 105 $

Apply the Wilcoxon signed rank statistic *manually* to the differences between the observations and 105.

d. Repeat part (c) using R. Conduct the 6 steps hypothesis testing as explained in the lecture based on the R output. 


**Question 3: Walpole 16.2.**   

The following data represent the number of hours of flight training received by 18 student pilots from a certain instructor prior to their first solo flight: 

9, 12, 18, 14, 12, 14, 12, 10, 16, 11, 9, 11, 13, 11, 13, 15, 13, 14 

a. Perform a  Wilcoxon Signed-Rank test at the 0.05 level of significance to test the instructor's claim that the median time required before his students' solo is 12 hours of flight training. Conduct the 6 steps hypothesis testing as explained in the lecture based on the R output. 

b. Use a t-test (with the 6 steps) for comparison.

**Question 4: Adapted from Moore et al (2017) **   

You are interested in determining if the average amount of time (in hours) that students spend on the Internet per day is greater than 2 hours. The data below are from a random sample of 11 students.

2.5,	100,	0.5,	1,	1.5,	3,	3.5,	4,	3,	4,	2.5

a. Explore the data. What did you notice from your preliminary analysis of the data?

b. Suppose you were to remove the second observation (value = 100), would a t procedure be appropriate for these data? If it is, use a t-test to evaluate whether students spend on the Internet per day is greater than 2 hours.

c. Suppose you were to remove the second observation (value = 100). Apply the Wilcoxon signed rank statistic using R to
the differences between the observations and 2 to evaluate whether students spend on the Internet per day is greater than 2 hours.

